### ISSUE TITLE
Pull requests

### ISSUE THREAD

**Issue by DigitallyBorn** [DigitallyBorn/Ubersicht-Git-Log#3]
@adamdehaven, do you want to start doing pull requests for new changes and assign them to each other? (I'm not saying we have to, I'm obviously not a control freak having given you access and all.)

**Comment by adamdehaven** [comment]
@DigitallyBorn I'm fine with whatever. It looks like you granted me access, so that's probably easiest for me. I just pushed a couple changes, mainly increasing the allowable characters in the `branch` container before the ellipsis, changed the font to Helvetica Neue so most Macs have the default font, and updated the screenshot to match the changes.

**Comment by DigitallyBorn** [comment]
No worries. It was more an offer than anything else. Keep on doing your thing.

**Comment by adamdehaven** [comment]
Actually I think I'll fork the project, and then submit pull requests in. If you don't mind, keep me as a contributor and that way I can merge my own pull requests. That way I can keep my fork separate from the master, but can easily make changes or suggest new features via pull request that we can then discuss. Sound good?

**Comment by DigitallyBorn** [comment]
Absolutely. Fire away.

**Comment by adamdehaven** [comment]
Sorry about all the pushes tonight, but I think everything looks great. If you don't care for any of the updates I made, open a new issue and I can back them out/make changes without losing everything.
